#pragma once

#include "Graphics.h"
#include "Vector2D.h"

/*
 *	Creates a texture containing providing text/font information and renders it to the
 *  screen. Can be locked into a certain position or render relative to the game world.
 * 
 *  Uses Latin1 rendering for now, no need for much else.
 */
class Text
{

private:

	std::string text;					// Raw Text to display.
	std::string fontName;				// File name of currently opened font.

	SDL_Texture* textTexture;			// Texture created from current text information.
	TTF_Font* font;						// Controls font type and letter size
	Vector2D* textureSize;				// Normal size of the currently loaded texture.
	Vector2D* scaleFactor;				// Amount to scale the texture that will be rendered.
	SDL_Rect destRect;					// Controls render position and size.
	SDL_Color textColor;				// Controls foreground color and alpha channel of text.
	
	int lineWidth;						// TTF Pixels until line will wrap to a new line.
	int fontSize;						// TTF Font Size.

public:


	Text(const char* fontFileName, const char* text, const Vector2D& pos = Vector2D(0, 0),
		const SDL_Color& fgCol = SDL_COLOR_SOLID_WHITE, const int& fontSize = 12, const int& lineWidth = 500);

	~Text();

	/*
	 *	Sets the text of the current text object.
	 * 
	 *  Calling this will rebuild the rendered texture, so do not
	 *  use too much or too often
	 */
	void UpdateText(const char* newText);

	/*
	 *	Move the position of the text by the given offset 
	 */
	void MoveText(const Vector2D& offset);

	/*
	 *	Renders the text to the screen, using a texture generated from the 
	 *  TTF texture in order to utilize SDL Rendering functions.
	 * 
	 *  If the given camera SDL_Rect is null, the text will render in screen space.
	 */
	void RenderText(const SDL_Rect* camera = nullptr, const double& angle = 0.0, const SDL_Point* pivot = nullptr);
	
	/*
	 *	Creates a texture from the surface generated by TTF_RenderText_Blended_Wrapped.
	 *	Pass scale in here 
	 */
	void BuildTexture();

	/*
	 *	Directly set position of text's destination rect.
	 */
	void Set_Position(const Vector2D& pos);

	/*
	 *	Set font of this object to a new font file.
	 * 
	 *  Calling this will close the previous font and rebuild the
	 *  corresponding texture.
	 */
	void Set_Font(const char* fontFileName);

	/*
	 *	Set size of the font of this object, opening a new font file to do so.
	 *
	 *  Calling this will close the previous font and rebuild the
	 *  corresponding texture.
	 */
	void Set_FontSize(const int& size);

	/*
	 *	Set the scale of the actual destination rect for the text. The size
	 *  of the texture depends of font size, so pass in a muliplier for the
	 *  text size (i.e. scale of (1.0, 1.0) is the normal size);
	 */
	void Set_TextSize(const Vector2D& scaleFactor);

	/*
	 *	Set the color of the texture. This can be safely used to change the text
	 *  color at runtime, as it modifies the texture that will be rendered rather
	 *  than the actual font object.
	 * 
	 *  The given color's alpha channel WILL also effect the text! Use
	 *  a value of 255 to make it fully visible.
	 */
	void Set_ForegroundColor(const SDL_Color& fgCol);
};